### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by dajomo** [IdentityServer/IdentityServer3.Admin#1]
Hi
The Core project won't build ATM due to the inclusion in the project of a missing file .\obj\TraceSourceLogProvider.cs.

Also the Host project doesn't build because of a reference to that missing file.

**Comment by Daforest** [comment]
+1

**Comment by iBoonz** [comment]
Hi, the Admin site is nog 100% ready for release, there are currently stil some small bugs, I wil try to fix them today. Thanks for the info :)

**Comment by iBoonz** [comment]
Hi, 

The problem is solved, together with other items :)

Have fun :)
