### ISSUE TITLE
Tracing/Logging not working

### ISSUE THREAD

**Issue by pawepaw** [IdentityServer/IdentityServer3.Admin#12]
Hello,

I simply downloaded repository and run application but there is no information logged. The file C:\logs\IdAdmin.svclog is not beeing even created. I don't have such problem with IdentityManager so access rights to logs folder are correct.

To make sure i've even called logger once to write something but it changes nothing.
 ``` 
ILog Logger = LogProvider.GetCurrentClassLogger();
Logger.Info("Logger test");
```

I've no idea why it isn't working because it looks pretty the same as in identitymanager.

**Comment by MAOliver** [comment]
@pawepaw There isn't a lot of information being logged, but the logger does work. I think you might be setting up the config wrong. 

An example using my local auth admin setup (using serilog as the provider) is below:

```csharp
namespace Auth.Admin.Api
{
    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            Log.Logger =
                 new Serilog.LoggerConfiguration().MinimumLevel.Debug()
                     .WriteTo.RollingFile(pathFormat: @"c:\logs\IdSvrAdmin-{Date}.log")
                     .CreateLogger();

            JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();
            app.UseCookieAuthentication(AuthAdminConfiguration.CreateCookieAuthenticationOptions());
            app.UseOpenIdConnectAuthentication(AuthAdminConfiguration.CreateOpenIdConnectAuthenticationOptions());

            app.Map(GlobalConfiguration.AuthAdminRoute, adminApp =>
            {
                adminApp.UseIdentityAdmin(AuthAdminConfiguration.CreateIdentityAdminOptions());
                adminApp.UseFileServer(AuthAdminConfiguration.CreateFileServerOptions());
            });
        }
    }
    
}
```

This gives me the following log output under c:\logs\IdSvrAdmin-20160108.log when I startup:

```
2016-01-08 09:55:03.314 -05:00 [Information] Starting IdentityAdmin configuration
```

You won't get much else out of it right now.

**Comment by pawepaw** [comment]
I didn't change anything from "sample" https://github.com/IdentityServer/IdentityServer3.Admin/blob/master/IdentityServer3.Admin/Host/Startup.cs
https://github.com/IdentityServer/IdentityServer3.Admin/blob/master/IdentityServer3.Admin/Host/Web.config

So it should write trace into xml file located it c:\logs\IdAdmin.svclog

When I used your code it's working but in identityManager it's working using trace listeners.

**Comment by iBoonz** [comment]
Logging is indeed limited, if needed, I will add more logging, but nevertheless, it works.
