### ISSUE TITLE
Delete client does not work.

### ISSUE THREAD

**Issue by oleksii-nimbus** [IdentityServer/IdentityServer3.Admin#13]
Hi,

It looks like there is a typo in IdentityServer3.Admin/IdentityServer3.Admin/Core/Assets/Templates/clients/edit.html (line 5):
Should be 
ng-submit="deleteClient(client)"
instead of 
ng-submit="deleteclient(client)"

**Comment by iBoonz** [comment]
hi @oleksii-nimbus , thanks for the feedback, I will fix this asap :).

**Comment by iBoonz** [comment]
Fixed :)

**Comment by oleksii-nimbus** [comment]
Thanks a lot:)
