### ISSUE TITLE
Client secrets value/type not shown

### ISSUE THREAD

**Issue by christophebourguignon** [IdentityServer/IdentityServer3.Admin#14]
Hi,

The client secrets are not shown correctly. 
In IdentityServer3.Admin/IdentityServer3.Admin/Core/Assets/Templates/clients/edit.html (line 33)
 it should be
`<td>{{clientSecret.data.type}}</td>`
 `<td>{{clientSecret.data.value}}</td>`
instead of 
`<td>{{clientIdentityProviderRestriction.data.provider}}</td>`

**Comment by iBoonz** [comment]
Hi, Thanks for the fix, I adjusted the repo and updated it
