### ISSUE TITLE
API doesn't seem to support IdentityServer integration

### ISSUE THREAD

**Issue by devdigital** [IdentityServer/IdentityServer3.Admin#16]
How is integration with IdentityServer designed? Presumably it's designed to share clients/scopes at the data store level (e.g. SQL Server) rather than at the API level?

The reason is that the IdentityServer3.Admin API only seems to be able to retrieve clients by primary key ID via /clients/{primaryKey} (e.g. clients/1), whereas if you're trying to implement a ClientStore in IdentityServer3 then it needs to find a client by client id (e.g. "my_client").

Could the API not use the client id instead of primary key? Then IdentityServer3 could retrieve clients/scopes from the IdentityServer3.Admin API rather than directly from a shared data store.

**Comment by iBoonz** [comment]
The admin project is created to manage the Scopes and clients. not to share them with IdentityServer.
