### ISSUE TITLE
Prerelease packages does not include all dependencies

### ISSUE THREAD

**Issue by 20John22** [IdentityServer/IdentityServer3.Admin#17]
Prerelease packages does not include all dependencies. Is that done on purpose ? For that reason dependent packages have to be installed manually even though main package have a list of required packages in package.config file.

**Comment by ManuelRauber** [comment]
Since the admin is in an early development state, we didn't take care about package dependencies yet. And btw. which pre release packages do you use? We don't push them to NuGet, yet.

**Comment by 20John22** [comment]
I have used Identity* Dev Feed "https://www.myget.org/F/identity/".

**Comment by ManuelRauber** [comment]
Ah, okay. Yes. That's absolutely a dev feed, where we won't care about correct dependencies at all. :)
