### ISSUE TITLE
ClientSecret API is expecting the hashed value

### ISSUE THREAD

**Issue by davidjrh** [IdentityServer/IdentityServer3.Admin#18]
If I'm not wrong, the ClientSecret API seems to expect hashed value as parameter (i.e. .SHA256()), instead of the clear client secret to hash on the server before persisting it to storage:

```
   POST /api/clients/{subject}/clientSecret
   {
     "Type": "string",
     "Value": "string",
     "Id": "string"
   }
```

This makes no sense since clients consuming the API are not going to have the same server machineKey, right?

**Comment by brockallen** [comment]
Client secrets are hashed before storing in the DB, yes. It's unrelated to machineKey.

**Comment by dcinzona** [comment]
Any way to include a "client secret generation service"?  i.e. the user submits a clear text secret and the service responds with the hashed value?  May simplify the entry UI, while maintaining confidentiality for already stored secrets.

**Comment by svrooij** [comment]
There seems to be a javascript library for this. https://caligatio.github.io/jsSHA/
That way you could add an extra button (HashValue) that would take the clear text Secret and create the Base64 Sha256 hash before even sending it to the server.

**Comment by dcinzona** [comment]
That "number of rounds" feature is awesome.

**Comment by svrooij** [comment]
Shall I try to add this library to the ClientSecrets page?
It would be a nice way to generate the Hash right in the browser before sending it to the server.

**Comment by dcinzona** [comment]
+1 @svrooij

**Comment by iBoonz** [comment]
Hi, It would indeed be a nice feature to add to the Admin page, I currently don't have the time to do this myself :)

**Comment by iBoonz** [comment]
Added support for client hashing with provided javascript library. is pushed to git.

**Comment by svrooij** [comment]
You're the best @iBoonz !!! My angular was a bit rusty, would have done it myself.
When can we expect this on nuget?

**Comment by iBoonz** [comment]
I want to add the scope secret and AlwaysIncludeInIdToken from the claims.
So when thats done, I can create a new build. Hoping in a week or so :).
