### ISSUE TITLE
Publish the latest updates to Nuget

### ISSUE THREAD

**Issue by dcinzona** [IdentityServer/IdentityServer3.Admin#19]
Would you be able to publish the latest updates to Nuget?  Right now, Admin.EntityFramework uses the Nuget package which doesn't have fixes for things like Client Secret, deleting clients, etc.
If I download the latest version of IdentityServer3.Admin and add it's Core project as a reference to Entity Framework Admin, everything works as expected.

**Comment by iBoonz** [comment]
@brockallen, is it possible to publish a new nuget package?

**Comment by brockallen** [comment]
NuGet now updated
