### ISSUE TITLE
Missing Tabs

### ISSUE THREAD

**Issue by dajomo** [IdentityServer/IdentityServer3.Admin#2]
Hi

When first running the host sample, I'm not able to see any tabs other than Properties when editing a client. Should I expect to be able to set the redirect uris etc, as those tabs are not visible?

Cheers
Dave

**Comment by iBoonz** [comment]
Hi Dajomo,

You can set every property of the client, there was just a small issue with the In memory client, that I used for example purpose. I fixed the problem and updated the git, now I should work :)

Have fun :)
