### ISSUE TITLE
IdentityServer3.Admin 1.0.0-beta4 does not have dll inside

### ISSUE THREAD

**Issue by farshid3003** [IdentityServer/IdentityServer3.Admin#20]
there is no dll in this package. did you forget it ????

**Comment by iBoonz** [comment]
@brockallen, is it possible to publish a new nuget package?

**Comment by farshid3003** [comment]
I check the package the dll is in the root. you should move it to the lib folder

**Comment by brockallen** [comment]
NuGet now updated
