### ISSUE TITLE
ipRestrictions tab does not update after adding items

### ISSUE THREAD

**Issue by MAOliver** [IdentityServer/IdentityServer3.Admin#21]
Steps to reproduce:

1. New Client, Name: whatever id: whatever
2. navigate to ipRestrictions tab
3. Add Client Identity Provider Restrictions: "idsrv"

Database is updated, but I have to navigate back to the search page and go back to "Edit" the client to get an updated list for that tab.

I did notice that my javascript console has the following error:

```javascript
TypeError: Cannot read property 'provider' of undefined
    at Scripts.Bundle.js:1049
    at Scripts.Bundle.js:117
    at m.$eval (Scripts.Bundle.js:131)
    at m.$digest (Scripts.Bundle.js:128)
    at m.$apply (Scripts.Bundle.js:132)
    at k (Scripts.Bundle.js:90)
    at v (Scripts.Bundle.js:95)
    at XMLHttpRequest.z.onreadystatechange (Scripts.Bundle.js:96)(anonymous function) @ Scripts.Bundle.js:111
```
Using latest version of Chrome.

Minor issue since the functionality is working and there is a workaround (navigate out and back in)

Let me know if you need more info.

**Comment by iBoonz** [comment]
Hi!

Thanks for the feedback :), I fixed the issue and updated the git, this will be available in the next nuget package

**Comment by brockallen** [comment]
NuGet now updated
