### ISSUE TITLE
While installing I am getting a Failed to update binding redirects

### ISSUE THREAD

**Issue by madhavabhyankar** [IdentityServer/IdentityServer3.Admin#22]
I am trying to install this package with IdentityServer and I am getting the error below.  I am doing something wrong?
Failed to update binding redirects for C:\Projects\PetProjects\Abhyankars\Abhyankars.AuthServer2\Abhyankars.AuthServer2\ : Duplicate type with name 'System.Web.Http.Properties.System.Web.Http.CommonWebApiResources' in assembly 'IdentityServer3.Admin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

I wonder if this has anything to do with .Net 4.5.2.  I rebuild the repo with this version and everything seems to be working

**Comment by brockallen** [comment]
I think we had a nuget issue -- can you try again (we just released an update).

**Comment by madhavabhyankar** [comment]
Looking good.

**Comment by ow-krioles** [comment]
I'm getting the same error when trying to run Host for Admin.EntityFramework in Visual Studio Community 2015. Host for Admin builds and runs fine.

**Comment by madhavabhyankar** [comment]
@ow-krioles The Host for Admin.EntityFramework uses Beta6.  I have submitted a patch to fix that.  In the meantime, you can update the packages for Host in Admin.EntityFramework to make it work.
