### ISSUE TITLE
Extending Admin Website

### ISSUE THREAD

**Issue by carl-thomas** [IdentityServer/IdentityServer3.Admin#23]
Would we be able to extend the website to include our own sections. e.g. At the moment we can manage Clients & Scopes but could we extend to include Users? I understand that everyone may store the users differently but it would be great if there was one place to show all the Clients, Scopes and Users and we built the Users interface ourselves.

**Comment by iBoonz** [comment]
Hi, 

We don't think that the User and Admin section should be in the same project. These are 2 different concepts to manage. Thats why we seperated these projects. 

If you want to have everything in one solution, you can add the nuget packages in your project.
