### ISSUE TITLE
Getting Config to update in realtime

### ISSUE THREAD

**Issue by parkinsona** [IdentityServer/IdentityServer3.Admin#25]
Hi Guys,

I just stumbled across this project and I'm very excited to see its happening.
My big question is:
Normally when a change is made to the idsvr options OWIN startup, it is not re-run by IIS unless a change to web.config is also made.

Will this admin tool force some kind of update so that the OWIN startup will reflect the changes in realtime?

**Comment by iBoonz** [comment]
Hi,

No, The admin just gets the data from the database and perisists the changes. Why should we want to reset the App Pool? Are you using in memory data?

**Comment by parkinsona** [comment]
I'm not using in memory data. I pull my client changes out of config and convert them during the IdentityServerServiceFactory creation that gets called from startup.

The problem I have, is the startup code that creates my IdentityServerOptions, only gets fired when I first load up the application, or when any change (could just be a space) is made to the web.config.

If the admin is just storing the settings and then identity server is retrieving those settings. Then how do you get the startup to fire again when you make a change to them?

**Comment by iBoonz** [comment]
Currently the admin repo only supports EntityFramework as persistance layer [Link](https://github.com/IdentityServer/IdentityServer3.Admin.EntityFramework)  so in your case you would need to implement a persistance layer for config files, to make use of the Admin site.

**Comment by parkinsona** [comment]
I don't think I'm explaining my situation very well.
I'd be more than happy to convert over to using EF as the persistance layer.

However, if I'm in a production environment that uses OWIN and I make changes in the admin site to my idsvr clients. Do I need to restart idsvr site or do anything for them to be reflected? At the moment, even if I use the inMemory samples from idsvr any changes I make to clients or scopes are only picked up if I also make a change to web.config. Otherwise they get ignored.

I basically am wanting to know if there's some way to trigger the OWIN startup code that reads the stored  configuration. My concern is that we could make use of idsvr Admin, but the changes won't be pulled into idsvr unless we do something to the site. In a production environment this changes how we could do our deployments. 

It would be awesome if I could make a change in idsvr admin, and idsvr has some way of knowing its been updated so it will rebuild the client and scope repos.

**Comment by iBoonz** [comment]
If your IdentityServer is looking at the same database as your admin site, every edit you do in the Admin site will immediately be done for the Idsrv. No  need to restart App Pools or owin applications

**Comment by parkinsona** [comment]
So in IdentityServer instead of having an in memory user service, you have one that references the database. Does this get queried everytime someone attempts to authenticate?

**Comment by iBoonz** [comment]
Ofcourse

**Comment by parkinsona** [comment]
Thank you very much. This sounds very promising.
I'll keep an eye on it and see if I can find time to implement it one day.

**Comment by iBoonz** [comment]
FYI, the Admin is only for clients and scopes. Use the IdentityManager to manage your roles and users,
