### ISSUE TITLE
Host admin in the same project as the IdentityServer

### ISSUE THREAD

**Issue by bjarteskogoy** [IdentityServer/IdentityServer3.Admin#29]
I keep getting infinite redirects when trying to set up this.
Is it possible? If so, could you help me out?

Now I'm hosting IdentityServer on "/id" and IdentityAdmin on "/admin".

If possible I would like to host the IdentityServer on the root and IdentityAdmin on "/admin".

**Comment by svrooij** [comment]
We have this working!! We used [this](https://github.com/zemacik/IdentityServer3-IdentityManger-IdentityServerAdmin-Sample/blob/master/MyIdentityServer/Startup.cs) as a starting point.
But infinite redirects sound like you forgot to add [cookieAuthentication](https://github.com/zemacik/IdentityServer3-IdentityManger-IdentityServerAdmin-Sample/blob/master/MyIdentityServer/Startup.cs#L31)

**Comment by bjarteskogoy** [comment]
Any more clues. Could you show me your startup file?
