### ISSUE TITLE
Error while loading default "/admin" page

### ISSUE THREAD

**Issue by jatpat** [IdentityServer/IdentityServer3.Admin#33]
Hi,

I downloaded latest code from repository and run project from visual studio, but I am getting error while opening default "/admin" page.

I have attached screenshot and text file contains link of the error for AngularJs.

Thanks.

[AngularJs Error link.txt](https://github.com/IdentityServer/IdentityServer3.Admin/files/206309/AngularJs.Error.txt)

![error](https://cloud.githubusercontent.com/assets/6779382/14315445/e09bff80-fc1a-11e5-9f61-edb8a1e1f573.png)

**Comment by iBoonz** [comment]
I am currently busy implementing Scope scecret and adding some claim properties, I must forgot something to include, this will be fixed with the next update :),

**Comment by jatpat** [comment]
OK, Fine

**Comment by DeezSmith** [comment]
This Error is from..
Assets/Scripts/App/ttidAdmScopes.js
` var app = angular.module("ttidAdmScopes", ['ngRoute', 'ttidAdm', 'ttidAdmUI', 'ui.bootstrap.datetimepicker'<---]);`

The UI Bootstrap.js file isn't included in the Project or any JS. I removed the reference and the Admin page loaded after rebuild

**Comment by iBoonz** [comment]
I Commited a new update, this is not the final product, but the error
should be gone :)

2016-04-06 19:12 GMT+02:00 Derek Smith <notifications@github.com>:

**Comment by jatpat** [comment]
Thank you,  it works
