### ISSUE TITLE
Customizing views/themes when using the Nuget package?

### ISSUE THREAD

**Issue by florindpreda** [IdentityServer/IdentityServer3.Admin#36]
I configured the Admin with EF by using the IdentityServer3.Admin nuget package. 

Going forward, what the best approach to customize the style of the views?
Can it be done by extending the application that uses the the Nuget package or I need to modify the IdentityAdmin project itself, build it and then reference it in the application that uses it?

**Comment by iBoonz** [comment]
There is currently no support to modify or extend the views, so you should modify the project itself and reference that in your application.

**Comment by florindpreda** [comment]
I understand. Thanks. 
Not sure if this is the right place to ask but is it the same with IdentityManager?

**Comment by iBoonz** [comment]
Yea, the IdentityManager core is basically the same as the Admin repo. 
The views and business logic have different implementations, there are some other admin specific things, but the core is the same

**Comment by florindpreda** [comment]
Ok. Thanks.
