### ISSUE TITLE
Unit Tests Failing

### ISSUE THREAD

**Issue by systemsymbiosis** [IdentityServer/IdentityServer3.Admin#4]
Hi,

I am observing many unit test failures. I attach a png file of my test runner window.

![identityserveradminunittests](https://cloud.githubusercontent.com/assets/533463/11603714/6864f1f8-9ae4-11e5-8b7e-5cc683656a94.png)

I am not really sure how to tackle this but if you give me a pointer I'll be happy to take a look.

**Comment by iBoonz** [comment]
Hi Austin,

Thanks for the feedback, I am aware of these problems. I did not have the time to fix these errors. I completed the EF Admin plugin yesterday with working UnitTests. I will try to fix the Admin core Tests this week. Feel free to adjust if necessairy :)

Best Regards
Bert

**Comment by systemsymbiosis** [comment]
Yes great work! Your efforts are appreciated. Thanks for confirming it is not something at my end.

I did run the EF Admin tests and was failing also. This was caused by not having the SQL Script that generates the DB. Maybe you could use the database auto creation capabilities in EF to set the DB up or maybe just include a DB creation script.

I could not quite work out how the tests in the Admin project were working. After debugging it looks like all seems to be set up pretty well but the mocks do not seem to return results as they should. On that basis most of the modifications would mean modifying FakeIdentityAdmin to ensure that it is returning the results as the tests expect. Correct?

I notice that there are a few commented out tests also. Does the plan include adding these? 

I am happy to take a look later and see if I can get any progress. Any pointers in the right direction are appreciated.

**Comment by iBoonz** [comment]
Hi Austin,

I just tested the EF unit test, and my solution does create a new database
when no database is found. EF wil create a new database if none is found,
so no script is needed.
The Admin project is basicly a revamp of the IdentityManager project, only
with another implementation, UI changes and slight core modifications.

The unit test project is also copied from the IdentityManager (that
explains the commented items), I started refactoring the project but did
not get it working, I kept on getting errors with the setup. I never worked
with Moq before :). so I cannot give any pointers, because I don't know why
it is failing, but I will find it, eventually.

Happy Programming! :)
Bert

2015-12-05 10:39 GMT+01:00 Austin Dimmer <notifications@github.com>:

**Comment by systemsymbiosis** [comment]
HI Bert,

I have taken a look at this but have not made great progress.

My feeling is that it is not possible to have a class like the following

```C#
public class FakeIdentityAdmin : Mock<IIdentityAdminService>

```

The following StackOverflow answer indicates: 

http://stackoverflow.com/questions/11738102/how-to-mock-non-virtual-methods

"Moq cannot mock non virtual methods on classes. Either use other mocking frameworks such as Type mock Isolator which actually weaves IL into your assembly or place an interface on EmailService and mock that."

So maybe it will be easier to let Mock just do the work here instead of creating a Fake implementation?
```C#
       public class WebApiTestBase
    {
        protected Mock<IIdentityAdminService> IdentityAdminImpl;
        protected TestServer Server;
        protected HttpClient Client;

        [TestInitialize]
        public void Init()
        {
            IdentityAdminImpl = new Mock<IIdentityAdminService>();
            Server = TestServer.Create(adminApp =>
            {
                var factory = new IdentityAdminServiceFactory
                {
                    IdentityAdminService = new Registration<IIdentityAdminService>(IdentityAdminImpl.Object)
                };
                adminApp.UseIdentityAdmin(new IdentityAdminOptions
                {
                    Factory = factory
                });
            });
            Client = Server.HttpClient;
        }
```

Just ideas. I may not be as well placed as you to debug this since you understand the codebase and what you want tested much better than me!

**Comment by iBoonz** [comment]
All Unit tests are passing now, currently the unit test are limited for Client Creation/Query/Delete and Client Claim creation/delete/Query, more will be added in the future

**Comment by systemsymbiosis** [comment]
Great job! Thanks.
