### ISSUE TITLE
Failed Test CreateClientAsync_IdentityAdminReturnsSuccess_CorrectResults

### ISSUE THREAD

**Issue by jkaellner** [IdentityServer/IdentityServer3.Admin#44]
Using the latest master zip, the test in Core.Tests\Api\ClientControllerTest.cs returns: 

Test Name:	CreateClientAsync_IdentityAdminReturnsSuccess_CorrectResults
Test FullName:	Core.Tests.Api.ClientControllerTests.CreateClientAsync_IdentityAdminReturnsSuccess_CorrectResults
Test Source:	C:\Users\username\Documents\Visual Studio 2015\Projects\IdentityServer3.Admin-master\source\Core.Tests\Api\ClientControllerTests.cs : line 79
Test Outcome:	Failed
Test Duration:	0:00:30.2918833

Result StackTrace:	
at System.Uri.get_AbsoluteUri()
   at Core.Tests.Api.ClientControllerTests.CreateClientAsync_IdentityAdminReturnsSuccess_CorrectResults() in C:\Users\username\Documents\Visual Studio 2015\Projects\IdentityServer3.Admin-master\source\Core.Tests\Api\ClientControllerTests.cs:line 88
Result Message:	
Test method Core.Tests.Api.ClientControllerTests.CreateClientAsync_IdentityAdminReturnsSuccess_CorrectResults threw exception: 
System.InvalidOperationException: This operation is not supported for a relative URI.

**Comment by iBoonz** [comment]
is fixed in 1.0.0-beta9
