### ISSUE TITLE
Documentation for setting up Admin server

### ISSUE THREAD

**Issue by gauravhub** [IdentityServer/IdentityServer3.Admin#46]
Hi,

I am looking for instructions for setting up Admin server but could not find any? Is there any tutorial / wiki with setup instructions?

Thanks,
Gaurav

**Comment by iBoonz** [comment]
You can download the git solution and explore the host project, Also the Admin is very similar to the identitymanager, and this got a nice wiki, so you can check that out.

**Comment by gauravhub** [comment]
Thank You
