### ISSUE TITLE
Plugin - IdentityServer3.EntityFramework

### ISSUE THREAD

**Issue by smuthiya** [IdentityServer/IdentityServer3.Admin#47]
#My understanding is, this Admin project works as in memory store, because 'InMemoryIdentityManagerService' class does not persist data to some store.

What I would like to do is store that information (Clients and Scopes) to MSSQL - for this in my IdentityServer I am using 'IdentityServer3.EnityFramework' nuget package. 

What is the way to plugin the same package in this project so that clients and scopes are persisted in DB?
Write my own class which implements the 'IIdentityAdminService' interfaces and then save the clients and scopes to db using entity framework/'IdentityServer3.EnityFramework'?

**Comment by iBoonz** [comment]
Or you could use the Admin.Entityframework project, this is a persistence layer for the Admin project: 
[IdentityServer3.Admin.EntityFramework](https://github.com/IdentityServer/IdentityServer3.Admin.EntityFramework) , just add the nuget package to your solution, and you can persist to SQL via EF. (there is a sample project in the git project)

**Comment by iBoonz** [comment]
Or you could use the Admin.Entityframework project, this is a persistence layer for the Admin project: 
IdentityServer3.Admin.EntityFramework , just add the nuget package to your solution, and you can persist to SQL via EF. (there is a sample project in the git project)
