### ISSUE TITLE
405 Method not allowed (POST)

### ISSUE THREAD

**Issue by bjarteskogoy** [IdentityServer/IdentityServer3.Admin#48]
The Project is running without issues when running locally With Visual Studio. When deploying to IIS or Azure I get a 405 Method not allowed (POST) when the identityserver is posting it's response back to the Identity admin.

Any suggestions?

**Comment by iBoonz** [comment]
Can you give us more information, a stacktrace and workflow, what flow are you using, is the client correctly configured?

**Comment by bjarteskogoy** [comment]
I have a web app on Azure With identityserver running as a Virtual Application in it's own subdirectory and the IdentityAdmin running in another Virtual Application in it's own subdirectory.

When runnin the identityadmin locally debug/no debug in Visual studio everything Works ok. When trying to log in I'm redirected to the identityserver, can log in and is redirected back to the identityadmin.

Identityadmin on Azure though fails on the last step. The last Messages in the identityserver log:
{
    "Timestamp": "2016-08-30T11:13:43.0631017+00:00",
    "MessageTemplate": "Posting to [...].com/scopeclientadmin",
    "Level": "Information",
    "Exception": null,
    "RenderedMessage": "Posting to [...].com/scopeclientadmin",
    "Properties": {
        "SourceContext": "IdentityServer3.Core.Results.AuthorizeFormPostResult"
    }
}
And:
{
    "Timestamp": "2016-08-30T11:13:43.2025604+00:00",
    "MessageTemplate": "CSP Report endpoint requested",
    "Level": "Information",
    "Exception": null,
    "RenderedMessage": "CSP Report endpoint requested",
    "Properties": {
        "SourceContext": "IdentityServer3.Core.Endpoints.CspReportController"
    }
}
And: 
{
    "Timestamp": "2016-08-30T11:13:43.2025604+00:00",
    "MessageTemplate": "CSP Report data: {0}",
    "Level": "Information",
    "Exception": null,
    "RenderedMessage": "CSP Report data: \"{\\\"csp-report\\\":{\\\"document-uri\\\":\\\"https://[...].com/identityserver/connect/authorize?client_id=idAdmin&redirect_uri=https%3A%2F%2F[...].com%2Fscopeclientadmin&response_mode=form_post&response_type=id_token&scope=openid%20idAdmin&state=OpenIdConnect.AuthenticationProperties%3DvSVth8KMmbtunvYZYkl64Sm_rwjbjY04NLRoOkBFeCYTyPgoVZ1Xb0R6IuehpYZFIgripx9-Eabg-mG2gYVFdyY_zdCSRc9-1hAxp7GTvWaqXfamVtO-BuxgKCpd9uPF0-_5zPObUy1MjQzDgEG_c4epldtih4Jw1hWKBWx25toBNAlzF1jSb7R6qnTo2CLY2K-A-z7fsl1BlfTjAWhn1tAbyHshACdkWOmY5Pbf4Tcm5mKjHWZwRUIZJWeMsh1_yn_lZsgcCpQP9NTqxzmDaM743FcMNrJ6ZXsfUrv9agVpNgZTvVKKnZGeoA8jpPQpl2x-tY9r2sJMmxNVkUfWgg&nonce=636081524180350050.ZDljMDg4ZmQtZTc3OC00YTY5LThhMWYtNmY4N2FhYWFjMGE2OWQ5ZDNiZTctMTRkMS00NDAwLWFiMjQtZGQ3YzYyYmI3YTMx\\\",\\\"referrer\\\":\\\"\\\",\\\"blocked-uri\\\":\\\"\\\",\\\"violated-directive\\\":\\\"script-src 'self'\\\",\\\"original-policy\\\":\\\"default-src 'self'; script-src 'self' ; style-src 'self' 'unsafe-inline' ; img-src *;  report-uri https://[...].com/identityserver/csp/report\\\"}}\"",
    "Properties": {
        "0": "{\"csp-report\":{\"document-uri\":\"https://[...].com/identityserver/connect/authorize?client_id=idAdmin&redirect_uri=https%3A%2F%2F[...].com%2Fscopeclientadmin&response_mode=form_post&response_type=id_token&scope=openid%20idAdmin&state=OpenIdConnect.AuthenticationProperties%3DvSVth8KMmbtunvYZYkl64Sm_rwjbjY04NLRoOkBFeCYTyPgoVZ1Xb0R6IuehpYZFIgripx9-Eabg-mG2gYVFdyY_zdCSRc9-1hAxp7GTvWaqXfamVtO-BuxgKCpd9uPF0-_5zPObUy1MjQzDgEG_c4epldtih4Jw1hWKBWx25toBNAlzF1jSb7R6qnTo2CLY2K-A-z7fsl1BlfTjAWhn1tAbyHshACdkWOmY5Pbf4Tcm5mKjHWZwRUIZJWeMsh1_yn_lZsgcCpQP9NTqxzmDaM743FcMNrJ6ZXsfUrv9agVpNgZTvVKKnZGeoA8jpPQpl2x-tY9r2sJMmxNVkUfWgg&nonce=636081524180350050.ZDljMDg4ZmQtZTc3OC00YTY5LThhMWYtNmY4N2FhYWFjMGE2OWQ5ZDNiZTctMTRkMS00NDAwLWFiMjQtZGQ3YzYyYmI3YTMx\",\"referrer\":\"\",\"blocked-uri\":\"\",\"violated-directive\":\"script-src 'self'\",\"original-policy\":\"default-src 'self'; script-src 'self' ; style-src 'self' 'unsafe-inline' ; img-src *;  report-uri https://[...].com/identityserver/csp/report\"}}",
        "SourceContext": "IdentityServer3.Core.Endpoints.CspReportController"
    }
}

And finally: 
{
    "Timestamp": "2016-08-30T11:13:43.2025604+00:00",
    "MessageTemplate": "Rendering 204",
    "Level": "Information",
    "Exception": null,
    "RenderedMessage": "Rendering 204",
    "Properties": {
        "SourceContext": "IdentityServer3.Core.Endpoints.CspReportController"
    }
}

**Comment by bjarteskogoy** [comment]
Figured it out ... Stupid of me.
The redirect url needs a trailing slash for the request to be handled correctly.
