### ISSUE TITLE
401 response while Login..

### ISSUE THREAD

**Issue by techdetail** [IdentityServer/IdentityServer3.Admin#49]
Hi,
  When i click on the login button of admin screen, I'm getting 401 unauthorized response.  I got the IdentityServer3.Admin as NuGet package inside my MVC project and trying to execute it, any idea on what might be the issue ?,  by the way if i download the git code and run it as it is , it is working fine..

http://localhost:50362/adm/authorize?state=20609424472425106&client_id=idAdmin&response_type=token

![pre 401](https://cloud.githubusercontent.com/assets/16840923/18059365/a73ef60a-6de6-11e6-826d-ce502095f8ea.png)

![401 error](https://cloud.githubusercontent.com/assets/16840923/18059309/710d186e-6de6-11e6-8636-f23bf2561ae4.png)

**Comment by iBoonz** [comment]
Did you correctly configured your MVC appilcation, added your the admin in
your MVC as a known client?
Check the host example to see how it can be done.

2016-08-29 18:48 GMT+02:00 techdetail <notifications@github.com>:

**Comment by iBoonz** [comment]
You could also enable the logs and check your logs

2016-08-29 19:56 GMT+02:00 bert hoorne <hoorneb@gmail.com>:

**Comment by techdetail** [comment]
I fixed it. Looks like some default properties in  AdminHostSecurityConfiguration was causing this error, previously i didn't have SSL enabled in my localhost and added the AdminHostSecurityConfiguration behavior. Now i have enabled the SSL and commented the 3 lines and it started working.., but not sure on which property exactly caused it to behave it this way..

(Commented line was enabled when i got the error)
   ```
         app.Map("/adm", adminApp =>
            {
                var factory = new IdentityAdminServiceFactory();
                factory.Configure();
                adminApp.UseIdentityAdmin(new IdentityAdminOptions
                {
                    Factory = factory,
                    //AdminSecurityConfiguration = new AdminHostSecurityConfiguration()
                    //{
                    //    RequireSsl = false,
                    //    HostAuthenticationType = IdentityAdmin.Constants.LocalAuthenticationType
                    //}
                 });
            });
```
