### ISSUE TITLE
Nuspec Authoring Error?

### ISSUE THREAD

**Issue by systemsymbiosis** [IdentityServer/IdentityServer3.Admin#5]
As an experiment I thought I'd attempt to integrate this Admin version with Membership Reboot using the Membership Reboot sample

https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/MembershipReboot

I observe the following error.

Could not install package 'IdentityServer3.Admin 1.0.0-beta1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

![membershiprebootidentitymanageradmin](https://cloud.githubusercontent.com/assets/533463/11613987/f36453ca-9c33-11e5-9786-3db8f104fea4.png)

I suspect the Nuspec file does not contain a targetFramework attribute somewhere. I can't see the Nuspec file anywhere in the source code. I assume that it has not yet been added.

**Comment by iBoonz** [comment]
Thanks again for the feedback, I added added the target framework to the
nuget framework and uploaded it to github
Hopes this solves the issue

2015-12-06 16:19 GMT+01:00 Austin Dimmer <notifications@github.com>:

**Comment by systemsymbiosis** [comment]
Good man. Appreciated. I'll give it another try. Sorry to be troubling you at the weekend!

**Comment by iBoonz** [comment]
Np :), You are helping making the project more stable ;). So nothing bad
about that

2015-12-06 21:13 GMT+01:00 Austin Dimmer <notifications@github.com>:

**Comment by systemsymbiosis** [comment]
Just FYI. I managed to get this working with the MembershipReboot sample.

Brief steps I took to get it working

1. Installed IdentityServer3.Admin package via Nuget
2. Copied the Config directory from IdentityServer3.Admin.EntityFramework into the MembershipReboot sample project

![membershiprebootidentitymanageradminworking](https://cloud.githubusercontent.com/assets/533463/11616368/2e4f99d2-9c79-11e5-9c01-0e6132a7a5c8.png)


3. Modified the Startup class Configuration method as follows

```C#
        public void Configuration(IAppBuilder app)
        {
            LogProvider.SetCurrentLogProvider(new DiagnosticsTraceLogProvider());
            Log.Logger = new LoggerConfiguration()
               .MinimumLevel.Debug()
               .WriteTo.Trace()
               .CreateLogger(); 
            
            var connectionString = "MembershipReboot";

            app.Map("/admin", adminApp =>
            {
                var factory = new IdentityManagerServiceFactory();
                factory.Configure(connectionString);

                adminApp.UseIdentityManager(new IdentityManagerOptions()
                {
                    Factory = factory
                });
            });

            app.Map("/adm", adminApp =>
            {
                var factory = new IdentityAdminServiceFactory();
                factory.Configure();
                adminApp.UseIdentityAdmin(new IdentityAdminOptions
                {
                    Factory = factory
                });
            });

            app.Map("/core", core =>
            {
                var idSvrFactory = IdSvr.Factory.Configure();
                idSvrFactory.ConfigureCustomUserService(connectionString);

                var options = new IdentityServerOptions
                {
                    SiteName = "IdentityServer3 - UserService-MembershipReboot",
                
                    SigningCertificate = IdSvr.Certificate.Get(),
                    Factory = idSvrFactory,
                    AuthenticationOptions = new AuthenticationOptions{
                        IdentityProviders = ConfigureAdditionalIdentityProviders,
                    }
                };

                core.UseIdentityServer(options);
            });
        }
```
4.  I ran into a bunch of Could not load file or assembly 'Autofac.Integration.WebApi, Version=3.4.0.0' type errors. These were resolved by installing the relevant Nuget packages. The list was something like

Autofac
Microsoft.AspNet.WebApi.Owin
Microsoft.Owin.StaticFiles
Autofac.Integration.WebApi
Microsoft.Owin.Security.OAuth

The diff file image shows some of the changes to packages.config in the MembershipReboot sample project.

I think IdentityServer3.Admin should include these dependencies or a variation thereof in the Nuspec file. I am happy to submit a pull request for this issue.

Once I resolved these the project ran OK and I could access MembershipReboot Admin under localhost/admin and IdentityServer admin under localhost/adm. Happy days!

**Comment by brockallen** [comment]
I'm confused -- MR has nothing to do with the IdSvr admin tool. The admin tool is for configuring IdentityServer Clients and Scopes in a database. Those are unrelated.

**Comment by systemsymbiosis** [comment]
Brock,

This was just an experiment I was looking at to perhaps ease the deployment (and cost) into an Azure Cloud service. Running IdSvr and MR on the same instance would help towards this goal. Surely I can't be the only one who thinks of doing such things?

Also it was a chance for me to build familiarity with this project by testing out various configurations as well. As a new user of these projects it is certainly confusing as to what does what and how all the pieces fit together as a whole. I have learned quite a bit by doing this but still have some way to go!
