### ISSUE TITLE
Sql script to populate Db with standard scopes

### ISSUE THREAD

**Issue by AlexFree** [IdentityServer/IdentityServer3.Admin#58]
Are there any script to populate database with standard scopes ?

**Comment by RichardSilveira** [comment]
Are u using EF Migrations? Already was look to it?
https://identityserver.github.io/Documentation/docsv2/ef/migrations.html

**Comment by AlexFree** [comment]
yeah, that is what i was looking for. tanks, couldn't googling this page for some reason.
