### ISSUE TITLE
Nuget package not installed properly

### ISSUE THREAD

**Issue by SaschaHerrmann** [IdentityServer/IdentityServer3.Admin#6]
Hi,
this Admin module is very much appreciated, especially for testing.
I have VS 2015 and pulling in the package does not add it to the references list. I cannot use the libraries. I do not want to add them by hand. 
I installed:
IdentityServer3.Admin.1.0.0-beta4
IdentityServer3.Admin.EntityFramework.1.0.0-beta3

Project:
.Net 4.6.1
and packages for IdentityServer3

Any idea why this happens?

**Comment by MAOliver** [comment]
@iBoonz Confirmed issue reported by @SaschaHerrmann 

packages.config is updated.
package is installed under \pacakges\IdentityServer3.Admin.1.0.0-beta4
package structure was not what I would expect:

```
\packages
    \IdentityAdmin.dll
    \IdentityServer3.Admin.1.0.0-beta4.nupkg
```

instead of:

```
\packages
    \lib
        \net45
            \IdentityAdmin.dll
    \IdentityServer3.Admin.1.0.0-beta4.nupkg
````

Some of the other IdentityServer3 projects use build scripts that handle the version / nuget push -- I'm assuming that's probably all that's missing here.

Until then, an available workaround is to install the nuget package then manually add the reference to the assembly in the package directory.

**Comment by enemaerke** [comment]
I can also confirm this issue in VS2015 in a asp.net 5 project. DNX seemingly imports the package but does not actually pick up the assembly (seem by expanding the references and seeing the IdentityServer3.Admin reference not having any dependencies). I can fix it locally by manually creating the folder structure in the dnx package folder mentioned by @MAOliver but that won't fly for buildserver and other devs.

Any plans to fix this?

**Comment by iBoonz** [comment]
This issue is planned to be solved, I first need to check with
Brock/Dominick on how to build the Identity related packages, so there is a
uniform way of publishing.



2016-01-08 11:11 GMT+01:00 Søren Enemærke <notifications@github.com>:

**Comment by enemaerke** [comment]
Sounds cool, good to know it's being handled (and thanks for providing the lib, very cool stuff). 

Am tentatively planning a DocumentDb persistencelayer simular to the EntityFramework stuff for our project, hoping to make it publicly available so others can plug it in to your stuff

**Comment by iBoonz** [comment]
Cool, sounds nice :). And its not my stuff, its our stuff ;)

2016-01-08 11:22 GMT+01:00 Søren Enemærke <notifications@github.com>:

**Comment by iBoonz** [comment]
@brockallen, is it possible to publish a new nuget package?

**Comment by brockallen** [comment]
NuGet now updated
