### ISSUE TITLE
Admin for IS4

### ISSUE THREAD

**Issue by ntthanh** [IdentityServer/IdentityServer3.Admin#61]
Hi Team,

Could you please let us know when the Admin for IS4 is released?

Best,
Thanh

**Comment by leastprivilege** [comment]
We don't have plans to build an OSS admin tool for IS4.

There will be a commercial option soon, see here:
https://www.identityserver.com/upcoming-products

**Comment by ntthanh** [comment]
Thanks for your quick feedback!
Best,
Thanh
