### ISSUE TITLE
Configuration documentation anywhere ?

### ISSUE THREAD

**Issue by msouphy** [IdentityServer/IdentityServer3.Admin#62]
Hi,

I stumbled upon the IdentityServer3.Admin solution and its related EntityFramework storage implementation, and wanted to integrate it into my current IdentityServer implementation but I'm having a hard time figuring out how to configure it in my OWIN Startup class. Any chance for a little documentation somewhere ?

Thanks.

Mathieu

**Comment by iBoonz** [comment]
try downloading the solution from git, there is a sample project
