### ISSUE TITLE
AdminSecurityConfiguration

### ISSUE THREAD

**Issue by farshid3003** [IdentityServer/IdentityServer3.Admin#7]
There is no document to configure security for admin
I tried to use this config :

            app.Map("/admin", adminApp =>
            {
                var factory = new IdentityAdminServiceFactory();
                factory.Configure();

                adminApp.UseIdentityAdmin(new IdentityAdminOptions
                {
                    Factory = factory,
                    AdminSecurityConfiguration = new ExternalBearerTokenConfiguration
                    {
                        AdminRoleName = "Admin",
                        //BearerAuthenticationType = 
                        
                        Audience = "/resources",
                        Issuer = "/",
                        Scope = "offline_access",
                        SigningCert = Certificate.Get()
                    }
                });
            });

but it forwards me to /authorize?state=5882233217917165&client_id=idAdmin&response_type=token
and HTTP 404 Page
would you please let me know how should I configure this?

**Comment by iBoonz** [comment]
The admin uses the same configuration as the IdentityManager 

For example, you can setup the security as following: 

<code>
 public void Configuration(IAppBuilder app)
        {
            app.UseCookieAuthentication(new Microsoft.Owin.Security.Cookies.CookieAuthenticationOptions
            {
                AuthenticationType = "Cookies",
            });

            app.UseOpenIdConnectAuthentication(new Microsoft.Owin.Security.OpenIdConnect.OpenIdConnectAuthenticationOptions
            {
                AuthenticationType = "oidc",
                Authority = IdentityServer URI,
                ClientId = "idAdmin",
                RedirectUri = ADMINURI,
                ResponseType = "id_token",
                UseTokenLifetime = false,
                Scope = "openid idAdmin",
                SignInAsAuthenticationType = "Cookies",
                Notifications = new Microsoft.Owin.Security.OpenIdConnect.OpenIdConnectAuthenticationNotifications
                {
                    SecurityTokenValidated = n =>
                    {
                        n.AuthenticationTicket.Identity.AddClaim(new Claim("id_token", n.ProtocolMessage.IdToken));
                        return Task.FromResult(0);
                    },
                    RedirectToIdentityProvider = async n =>
                    {
                        if (n.ProtocolMessage.RequestType == Microsoft.IdentityModel.Protocols.OpenIdConnectRequestType.LogoutRequest)
                        {
                            var result = await n.OwinContext.Authentication.AuthenticateAsync("Cookies");
                            if (result != null)
                            {
                                var id_token = result.Identity.Claims.GetValue("id_token");
                                if (id_token != null)
                                {
                                    n.ProtocolMessage.IdTokenHint = id_token;
                                    n.ProtocolMessage.PostLogoutRedirectUri = RedirectURI
                                }
                            }
                        }
                    }
                }
            });


            app.Map(/admin, adminApp =>
            {
                var factory = new IdentityAdminServiceFactory();
                factory.Configure();
                adminApp.UseIdentityAdmin(new IdentityAdminOptions
                {
                    Factory = factory,
                    AdminSecurityConfiguration = new AdminHostSecurityConfiguration
                    {
                        HostAuthenticationType = "Cookies"
                    }
                });
            });
        }
</code>

**Comment by farshid3003** [comment]
Thank you

**Comment by fcartu** [comment]
Hi @iBoonz, I used that configuration and I'm able to login but when IS redirect me back I'm getting this error: **Error: You are not authorized to use this service.** 
What I'm missing?

**Comment by iBoonz** [comment]
Can you check your logs on c:\logs , you will findmore info why you are not authorized

**Comment by fcartu** [comment]
@iBoonz in my logs file there is nothing about the error. This is my startup file:
```
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
{
                Authority = Constants.BaseAddress,
                ClientId = Constants.ClientId,
                Scope = Constants.Scopes,
                RedirectUri = Constants.ProjectRedirectUri,
                ResponseType = "id_token",
                SignInAsAuthenticationType = "Cookies",
                UseTokenLifetime = false,

                Notifications = new OpenIdConnectAuthenticationNotifications
                {
                    SecurityTokenValidated = n =>
                    {
                        n.AuthenticationTicket.Identity.AddClaim(new Claim("id_token", n.ProtocolMessage.IdToken));
                        return Task.FromResult(0);
                    },
                    RedirectToIdentityProvider = async n =>
                    {
                        if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
                        {
                            var result = await n.OwinContext.Authentication.AuthenticateAsync("Cookies");
                            if (result != null)
                            {
                                var id_token = result.Identity.Claims.GetValue("id_token");
                                if (id_token != null)
                                {
                                    n.ProtocolMessage.IdTokenHint = id_token;
                                    n.ProtocolMessage.PostLogoutRedirectUri = Constants.ProjectRedirectUri;
                                }
                            }
                        }
                    }
                }
            });
// IdentityServer Main Configuration
            app.Map("/core", id =>
            {
                var viewOptions = new DefaultViewServiceOptions();
                viewOptions.CustomViewDirectory = customLoginPath;

                var factory = new IdentityServerServiceFactory()
                                    .Configure(connectionString);
                factory.ConfigureDefaultViewService(viewOptions);

                id.UseIdentityServer(new IdentityServerOptions
                {
                    SiteName = customSiteName,
                    SigningCertificate = prodecoSigningCertificate,
                    RequireSsl = false,

                    Factory = factory
                });
            });

            app.Map("/admin", adminApp =>
                {
                    var factory = new IdentityAdminServiceFactory();
                    factory.Configure();

                    adminApp.UseIdentityAdmin(new IdentityAdminOptions
                    {
                        Factory = factory,
                        AdminSecurityConfiguration = new AdminHostSecurityConfiguration()
                        {
                            RequireSsl = false,
                            HostAuthenticationType = IdentityAdmin.Constants.CookieAuthenticationType
                        }
                    });
                });
```

**Comment by gzlboy** [comment]
@fcartu Hi,did you fix it?

**Comment by fcartu** [comment]
Hi @gzlboy, this is the code I've been using. You need to add an AdminRole to your user see AdminRolName property. Let me know if you need help.

```csharp
app.UseIdentityManager(new IdentityManagerOptions() 
{
    Factory = new IdentityManagerServiceFactory()
         .Configure(connectionString, managerDefaultSchema)
    SecurityConfiguration = new HostSecurityConfiguration()
    {
        HostAuthenticationType = IdentityManager.Constants.CookieAuthenticationType,
        AdminRoleName = "IdentityServerManager",
        NameClaimType = "name",
        RoleClaimType = "role"
    }
});
```
