### ISSUE TITLE
Host Project Visual Studio 2017 Project file cannot be loaded

### ISSUE THREAD

**Issue by BruceHunter** [IdentityServer/IdentityServer3.Admin#70]
`  <Import Project="$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets" Condition="'$(VSToolsPath)' != ''" />
`

was not found.

**Comment by BruceHunter** [comment]
I fixed the issue by adding the following to the Host proj xml
'  <PropertyGroup>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">10.0</VisualStudioVersion>
    <VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
  </PropertyGroup>'

**Comment by psmyda** [comment]
Thanks @BruceHunter !!!

**Comment by BruceHunter** [comment]
No problem.
