### ISSUE TITLE
Is this the new IdentityManager?

### ISSUE THREAD

**Issue by huysentruitw** [IdentityServer/IdentityServer3.Admin#9]
I ask this because we're also planning to create an open-source project based on IdentityServer3 v2 with administrator support but also with user self-service support. The idea is to have a standalone OpenID Connect solution like pingidentity.com, auth0.com or Azure Active Directory B2C.

So I wonder what the roadmap/features are for this project or if it is just a revamped IdentityManager?

**Comment by brockallen** [comment]
No. This is just the admin piece for the IdentityServer scopes and clients if you plan to use a database for that data. It's unrelated to managing the users and unrelated to IdentityManager.

**Comment by leastprivilege** [comment]
...and instead of building something new - it would be more appropriate to rather contribute to the base.

**Comment by huysentruitw** [comment]
Contributing sounds perfect. Is there any project in particular that you know of or do you mean contributing this to IdentityManager itself?

**Comment by brockallen** [comment]
Well, I think he means these projects (both this repo for the IdentityServer Admin UI, and IdentityManager). And just so we're clear, these two projects are deliberately separate, but of course can be used together.

**Comment by huysentruitw** [comment]
I would still have to add a third project to add user self-service as users should be able to manage their applications, credentials and link/unlink their external identities.

We then might need a 4th project to combine all of these because we want a self-contained solution that can be deployed without having to change any line of code. It should start out of the box with a predefined admin user and everything should be configurable through the web-interface.

**Comment by leastprivilege** [comment]
Every project on its own is OWIN middleware which enables composability - maybe that is a good research topic to start with.

**Comment by huysentruitw** [comment]
Combining IdentityServer3 with WebAPI and static file/embedded file hosting is not that straightforward with OWIN, it is not plug and play.

**Comment by huysentruitw** [comment]
This is our current startup f.e.

    // The order is very important, if we call UseIdentityServer first, then models posted to
    // the manager Web API are not converted anymore.
    app.Map("/api", apiApp => apiApp.UseIdentityServerWebApi());

    // We need to map UseIdentityServer to a sub-path, otherwise the the FileServer middleware
    // can't host index.html on the root url.
    app.Map("/id", IdentityServer3.Configure);

    // Must come after WebApi and IdentityServer3
    FileServer.Configure(app);

    // Needed to make UseFileServer/UseStaticFiles work until vNext arrives.
    // See http://katanaproject.codeplex.com/wikipage?title=Static%20Files%20on%20IIS
    app.UseStageMarker(PipelineStage.MapHandler);

Second comment about mapping IdentityServer is no longer needed I guess, since now when `EnableWelcomePage = false`, the route is no longer registered. Anyway the other comments show how fragile the OWIN pipeline is :)

**Comment by huysentruitw** [comment]
Oh btw, I initially didn't want to discuss about whether or not we will start with the project. But now we got to it, I don't feel a lot of support for it either or did I misinterpret this?

I remember people asking for such a solution and now when we see those OpenID Connect cloud services rising, it might mean the end for the IdentityServer project, because getting IdentityServer working in a production environment still needs a lot of knowledge, effort and resources.

**Comment by leastprivilege** [comment]
This is the new admin project - @iBoonz currently works on it on its own - so your help would be very much appreciated.

We won't merge the Admin UI and IdentityManager - because all the projects we did so far, no-one ever used both functionalities in a single tool (separation of concerns).

So please get in touch with @iBoonz so he can tell you how to help out.
